version: "2.2"
services:
  jobmanager:
    image: docker.m.daocloud.io/flink:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: docker.m.daocloud.io/flink:latest
    restart: unless-stopped
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
